name: Bump Version
on:
  push:
    branches: "main"

jobs:
  auto-version:
    name: bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GarnerCorp/build-actions/bump-version@test-real-world
        id: bump
        with:
          version-type: "node"
          version-file-path: "package.json"
          git-name: "User"
          git-email: "user@example.com"
          major: major
          minor: minor
          debug: true
