name: Bump Version
on:
  push:
    branches: "main"

jobs:
  auto-version:
    name: bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: SpecialThing44/build-actions/bump-version@automatic-version-bumping
        id: bump
        with:
          version-type: "sbt"
          version-file-path: "version.sbt"
          git-name: "User"
          git-email: "user@example.com"
          major: major
          minor: minor
          debug: true
